<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Alekh" failures="1" tests="2" name="TestRunnerBlock.AddNewFunction" time="113.496" errors="0" timestamp="2023-08-28T22:36:24 IST" skipped="0">
  <testcase classname="TestRunnerBlock.AddNewFunction" name="runScenario" time="58.190"/>
  <testcase classname="TestRunnerBlock.AddNewFunction" name="runScenario" time="55.306">
    <failure message="expected [All Customers] but found [Maruti Suzuki692]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [All Customers] but found [Maruti Suzuki692]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at RepositoryOfAllPages.TasksPageRepo.isParticularCustNameShowing(TasksPageRepo.java:72)
at StepDefinationBlock.AddNewTest.i_should_see_that_particular_customer_name_as_in_task_list_page(AddNewTest.java:108)
at âœ½.i should see that particular customer name as "Maruti Suzuki" in Task list page(file:///C:/Users/Dell/Desktop/Cucumber/ActTIme/./src/main/java/FeatureFiles/AddNew.feature:42)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunnerBlock.AddNewFunction -->
